// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKBxgOWjzmbzJVUiKmip2lI6H3EiMLQYU',
    appId: '1:578698359:android:19ba7f0a30414bb8295a72',
    messagingSenderId: '578698359',
    projectId: 'codeverse-e2a04',
    storageBucket: 'codeverse-e2a04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLRCMRmdljbn1NXr31jBHphm08nq6CKMs',
    appId: '1:578698359:ios:37397dedf085cc47295a72',
    messagingSenderId: '578698359',
    projectId: 'codeverse-e2a04',
    storageBucket: 'codeverse-e2a04.firebasestorage.app',
    androidClientId: '578698359-jteug506rhh3f06989mq70fol76pp97v.apps.googleusercontent.com',
    iosClientId: '578698359-7mknt1akuvrrlu3vus7b8rg0p6pafbel.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeverse',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkqrniYX9ijmPlThCM0s_M64MG-5ORwIg',
    appId: '1:578698359:web:c87765e318ea21fd295a72',
    messagingSenderId: '578698359',
    projectId: 'codeverse-e2a04',
    authDomain: 'codeverse-e2a04.firebaseapp.com',
    storageBucket: 'codeverse-e2a04.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLRCMRmdljbn1NXr31jBHphm08nq6CKMs',
    appId: '1:578698359:ios:37397dedf085cc47295a72',
    messagingSenderId: '578698359',
    projectId: 'codeverse-e2a04',
    storageBucket: 'codeverse-e2a04.firebasestorage.app',
    androidClientId: '578698359-jteug506rhh3f06989mq70fol76pp97v.apps.googleusercontent.com',
    iosClientId: '578698359-7mknt1akuvrrlu3vus7b8rg0p6pafbel.apps.googleusercontent.com',
    iosBundleId: 'com.example.codeverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkqrniYX9ijmPlThCM0s_M64MG-5ORwIg',
    appId: '1:578698359:web:b84261a43144bc19295a72',
    messagingSenderId: '578698359',
    projectId: 'codeverse-e2a04',
    authDomain: 'codeverse-e2a04.firebaseapp.com',
    storageBucket: 'codeverse-e2a04.firebasestorage.app',
  );

}